### ISSUE TITLE
Please update npm

### ISSUE THREAD

**Issue by StoneCypher** [dundalek/GrammKit#11]
Fixing the `ohmjs` dep is great, except that if I install from GH, I get the same problem 😆 

Would you be kind enough to bump and push to NPM please?

**Comment by dundalek** [comment]
Good point, I published `v0.6.1`.

**Comment by StoneCypher** [comment]
Fantastic.  Thank you :)

**Comment by StoneCypher** [comment]
lol i wasn't even able to upgrade or uninstall grammkit

i had to hand edit package, nuke `node_modules`, remove `package-lock`, clear my `npm cache`, and reinstall 

all's well now.  thanks again

```
Johns-MacBook-Pro:fslp john$ npm uninstall --save-dev grammkit
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: ohm-js@github:harc/ohm#b7db5de9c68e62dd053ebc535c3dbec348e039bb.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/john/.npm/_logs/2018-02-05T17_09_48_813Z-debug.log
```
