### ISSUE TITLE
Is there a forum where I can get some help with Grammkit?

### ISSUE THREAD

**Issue by RayOffiah** [dundalek/GrammKit#26]
Hi there.

I'm trying to integrate Grammkit with AsciiDoctor, and I have run into a snag or two. Is there a forum where I can ask questions?

**Comment by RayOffiah** [comment]
S'kay. I can see where I was going wrong 😑

**Comment by dundalek** [comment]
Hi, this is a small hobby project so it does not have a community around it. You can always open an issue. If it is something straightforward I might be able to give some pointers, or it can always turn out there is a bug that needs to be fixed.

**Comment by RayOffiah** [comment]
Thanks for getting back to me.

 I’m looking integrate Grammkit with Asciidoc, and I got a little stuck. Seemed to have found my through it, though. Thanks 👍🏾

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
