### ISSUE TITLE
Any reason why Grammkit fails with a valid grammar?

### ISSUE THREAD

**Issue by RayOffiah** [dundalek/GrammKit#27]
Hi again.

I'm trying to run a couple of grammars through Grammkit, and they seem to be failing for some reason.

I've attached one of the file I was testing.

Oddly enough, I can't get it to work here either:

https://dundalek.com/grammkit/

It looks valid enough, so I'm a bit stuck.

```ebnf

tcl-statement ::= begin-transaction
                | set-transaction
                | savepoint
                | rollback-transaction
                | commit-transaction


begin-transaction ::= ( 'BEGIN' | 'START' ) ( 'WORK' | 'TRAN' | 'TRANSACTION' )
                      ( 'ISOLATION' 'LEVEL' 'READ' 'COMMITTED' )?

set-transaction ::= 'SET' 'TRANSACTION' 'ISOLATION' 'LEVEL' 'READ' 'COMMITTED'

savepoint ::= 'SAVEPOINT' savepointname

rollback-transaction ::= 'ROLLBACK' ( 'WORK' | 'TRAN' | 'TRANSACTION' )?
                       ( 'TO' 'SAVEPOINT' savepointname )?


commit-transaction ::= 'COMMIT' ( 'WORK' | 'TRAN' | 'TRANSACTION' )?

savepointname ::= identifier
```

**Comment by dundalek** [comment]
The error one gets is `Expected "::=", [a-zA-Z0-9_], comment, end of line, or whitespace but "-" found.` which contains the clue `but "-" found` which means there is an unexpected dash (it unfortunately does not print location which sounds like possibility for improvement).

The issue are the dashes which cannot be part of identifiers. You can fix it by replacing all `-` with `_`, e.g. `tcl-statement` becomes `tcl_statement`.

**Comment by RayOffiah** [comment]
Dammit! Another false alarm!

Thank you!
