### ISSUE TITLE
Uncaught TypeError: Cannot read property 'usedBy' of undefined

### ISSUE THREAD

**Issue by ustegrew** [dundalek/GrammKit#3]
Hi! Many thanks for this excellent work! 

Bug report and suggested fix:
- I observed an exception when diagramming the following PEG:

```
          start = num
          num = [0-9]+
          whtspace = ([ ]+)
```
- Exception observed
      `
      Uncaught TypeError: Cannot read property 'usedBy' of undefined
  `
- Origin
      Unused rule in given grammar: `whtspace`
- To reproduce
  - Navigate to Grammkit's  [online editor](http://dundalek.com/GrammKit/)
  - Paste offending grammar snippet into text box.
  - Exception will appear in the browser's web console (Chromium, in my case).
- Suggested fix: Include `typeof` guards
  - In `app/app.js::87`
    
    ```
    // Currently
    {references[rule.name].usedBy.length > 0 && <div>
    
    // Replace by
    {typeof references[rule.name] !== "undefined" && references[rule.name].usedBy.length > 0 && <div>
    ```
  - In `app/app.js::92`
    
    ```
    // Currently
    {references[rule.name].references.length > 0 && <div>
    
    // Replace by
    {typeof references[rule.name] !== "undefined" && references[rule.name].references.length > 0 && <div>
    ```

Hope this helps! Keep up the good work!

**Comment by dundalek** [comment]
Thanks for the detailed report, it is now fixed.

**Comment by ustegrew** [comment]
Your'e welcome! Thank you for the fix!
