### ISSUE TITLE
Generate SVGs as separate files

### ISSUE THREAD

**Issue by seagreen** [dundalek/GrammKit#5]
Just a suggestion, but GrammKit might be more useful if SVGs were generated as separate files from `<output>.html`. They could still be included in the output file, but then people who wanted to use them differently (say by linking to them, possibly out of order, in a README) could easily do so.

**Comment by dundalek** [comment]
Thanks, that's a good idea. Do you think it would make sense to add option to export to markdown which creates those separate files and then a markdown file that includes them in order? That way people could use them in READMEs or pick out individually.

**Comment by seagreen** [comment]
@dundalek: that sounds fantastic. It's a little more than I need for my situation (since I'll be writing my own markdown for the README), but I could definitely see people finding it useful.

**Comment by dundalek** [comment]
I published a new version `v0.5.0`. You can run `grammkit -t md yourgrammar.peg` which will output a markdown file and separate SVG files. If you want to extract the list of files in the original order you can use unix friends like `sed -n 's/## \(.*\)/\1.svg/p' yourgrammar.md`. Let me know if you find any issues.

**Comment by seagreen** [comment]
🎉 🎉 🎉 

Works great! Also, I added you to my [BNF-tools summary](https://github.com/seagreen/state-of-haskell-bnf) page. It's only supposed to be Haskell programs, but since there isn't a Haskell lib to do this I put GrammKit on anyway.

**Comment by dundalek** [comment]
Cool, thanks.
