### ISSUE TITLE
Grammar target using query parameter

### ISSUE THREAD

**Issue by sudo-suhas** [dundalek/GrammKit#7]
Is it possible to specify the grammar file to be loaded using query parameter? It's easier to share links that way.

**Comment by dundalek** [comment]
What would be the advantages compared to currently passing it in a hash?

**Comment by sudo-suhas** [comment]
Correct me if I am wrong but isn't the hash used for anchors for the parsed grammar? I am trying to specify the grammar file via url.

**Comment by sudo-suhas** [comment]
I apologise. I should have tried one of the example files loaded via URL.

**Comment by dundalek** [comment]
That's a good point though, having it as query param would allow links to also point to specific grammar rule.

**Comment by sudo-suhas** [comment]
Hmm.. I didn't think of that. Would be nice to have. I don't need it though.

Maybe you could have a line or so explaining how to specify file in URL? Just an example should be sufficient.
