### ISSUE TITLE
Install on windows

### ISSUE THREAD

**Issue by 3spGon** [dundalek/GrammKit#8]
Hi, I would like to know how to install it in window 10, show me this mistake: 
![error](https://user-images.githubusercontent.com/22010674/29578615-110cee74-872d-11e7-9b6a-f20bb156534c.PNG)

**Comment by dundalek** [comment]
Hi, thanks for the report. It fails due to [external dependency](https://github.com/harc/ohm/issues/205). It is for work in progress feature so I removed it for now and published updated version.

Please try it again, it should be fixed now.

**Comment by dundalek** [comment]
Closing for now, please create a new issue or reopen if another problem on windows appears.
